INSERT INTO CATS (ID, NAME, GENDER, WEIGHT) VALUES (1, 'Tom', 'MALE', 17.00);
INSERT INTO CATS (ID, NAME, GENDER, WEIGHT) VALUES (2, 'Luisa', 'FEMALE', 25.75);
INSERT INTO CATS (ID, NAME, GENDER, WEIGHT) VALUES (3, 'Manson', 'MALE', 22.75);
INSERT INTO CATS (ID, NAME, GENDER, WEIGHT) VALUES (4, 'Marta', 'FEMALE', 32.75);
INSERT INTO CATS (ID, NAME, GENDER, WEIGHT) VALUES (5, 'Zara', 'FEMALE', 20.15);
INSERT INTO CATS (ID, NAME, GENDER, WEIGHT) VALUES (6, 'Don', 'MALE', 30.00);

ALTER SEQUENCE hibernate_sequence RESTART WITH 7;
