CREATE TABLE DOGS (
  ID DECIMAL(10) AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NICK VARCHAR(255) NOT NULL,
  BREED VARCHAR(255) NOT NULL,
  GENDER VARCHAR(10),
  WEIGHT DECIMAL(5,2)
);

INSERT INTO PUBLIC.DOGS (NICK, BREED, GENDER, WEIGHT) VALUES ('Bill', 'Labr', 'MALE', 100.23);
INSERT INTO PUBLIC.DOGS (NICK, BREED, GENDER, WEIGHT) VALUES ('Lilly', 'Labr', 'FEMALE', 50.23);
INSERT INTO PUBLIC.DOGS (NICK, BREED, GENDER, WEIGHT) VALUES ('John', 'Rotv', 'MALE', 200.23);
INSERT INTO PUBLIC.DOGS (NICK, BREED, GENDER, WEIGHT) VALUES ('Paul', 'Mops', 'MALE', 70.23);
INSERT INTO PUBLIC.DOGS (NICK, BREED, GENDER, WEIGHT) VALUES ('Ann', 'Corgi', 'FEMALE', 40.70);

select * from dogs;

update PUBLIC.dogs set weight = weight + 20 where GENDER = 'FEMALE';

select * from dogs where breed <> 'Labr' ORDER BY id;
select id, nick as name from dogs where breed <> 'Labr' ORDER BY id;

CREATE TABLE LOGINS
(
  LOGIN VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX "logins_login_uindex" ON LOGINS (LOGIN);

INSERT INTO PUBLIC.LOGINS (LOGIN, PASSWORD) VALUES ('user2', '123456789');
INSERT INTO PUBLIC.LOGINS (LOGIN, PASSWORD) VALUES ('user1', 'one more pass');
INSERT INTO PUBLIC.LOGINS (LOGIN, PASSWORD) VALUES ('admin', 'pass1');

SELECT * from logins;

